name: Screenshots
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare_crc:
    runs-on: ${{ (github.repository == 'numworks/epsilon-internal') && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: build/setup.sh --only-simulator
      - name: Build PR head
        run: make -j32 PLATFORM=simulator ASSERTIONS=1 epsilon.bin
      - name: Compare screenshot images
        run: python3 build/screenshots/compare_crc.py output/release/simulator/linux/epsilon.bin
      - name: Upload output
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: output_compare_crc
          path: compare_crc_output_*/
          retention-days: 7
